### ISSUE TITLE
Only sync siblings.

### ISSUE THREAD

**Issue by simonseddon** [ginader/syncHeight#15]
Is there a way to restrict syncing the height of elements to just the tallest **sibling**?

At the moment I have elements being matched in a few different sections of the page, but they're all being set to the tallest matching element page-wide (sibling or not).

**Comment by krilor** [comment]
I haven't done any tests, but it seems to me that a solution for this would be to use some sort of jQUery selector that only pass a set of siblings to the script.

**Comment by ginader** [comment]
Thank you @simonseddon for the good question and to @krilor for the perfect answer! See the new example code [here](https://github.com/ginader/syncHeight/blob/master/index-sync-siblings-only.html) and running [here](https://cdn.rawgit.com/ginader/syncHeight/master/index-sync-siblings-only.html)

**Comment by simonseddon** [comment]
@ginader @krilor Good stuff!
